import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ToggleTheme } from "@/components/lightswind/toggle-theme";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} antialiased max-w-4xl mx-auto min-h-screen font-sans px-4`}
      >
        <ToggleTheme duration={600} animationType="diag-down-right" />
        {children}
        <footer className="border-t mt-18 flex items-center justify-center pt-8 pb-4">
          <p className="text-sm font-medium flex flex-col items-center gap-2">
            © 2026 Jelmar Rapis. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
