import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./global.css";
import NavBar from "./components/NavBar";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetBrains = Space_Grotesk({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--font-jet-brains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetBrains.variable} antialiased relative`}
      >
        <div className="max-w-5xl mx-auto sticky top-0 z-40">
          <NavBar />
        </div>
        <div className="max-w-4xl mx-auto min-h-screen px-4 mb-6">
          {children}
        </div>
      </body>
    </html>
  );
}
